name: Publish Release

on:
  push:
    branches:
      - master

jobs:
  build_7yuv_snap:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          use_lxd: true
      - name: Build Snap package
        run: |
          #snap install lxd
          cd snap
          sg lxd -c 'snapcraft --use-lxd'
