name: Publish Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
    - name: Build Snap package
      run: cd snap;snapcraft --debug
